instances: ["mongodb", "catalogue" ,"mysql", "rabbitmq", "user", "cart", "shipping", "payment", "frontend"] 
image_id: "ami-0220d79f3f480ecf5"
domain_name: "malshi.online" 
action: "create"
group_id: "sg-0e85d62ab28eb894d"
zone_id: "Z07103112YA8CK7NN1S5X"
mongodb_host: "mongodb.malshi.online"
catalogue_host: "catalogue.malshi.online"
user_host: "mongodb.malshi.online"
cart_host: "mongodb.malshi.online"
shipping_host: "mongodb.malshi.online"
payment_host: "mongodb.malshi.online"
