- name: catalogue setup
  hosts: catalogue 
  become: yes 
  tasks:

  - name: disable nodejs default module 
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable nodejs:20 module 
    ansible.builtin.command: dnf module enable nodejs:20 -y  

  - name: install nodejs
    package:
      name: nodejs
      state: present 
    
  - name: create roboshop system user
    user:
      name: roboshop 
      system: true 
      create_home: true 
      shell: /sbin/nologin
      state: present
      comment: "roboshop system user"

  - name: create /app directory 
    file:
      path: /app
      mode: '777' 
      state: directory

  - name: download the zip 
    shell:
      curl -o /tmp/catalogue.zip https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip &&
      cd /app && 
      unzip /tmp/catalogue.zip 
  
  - name: cd /app and install npm 
    command: npm install
    args:
      chdir: /app
  
  - name: copy catalogue service
    copy: 
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service
  
  - name: systemd reload 
    command: systemctl daemon-reload 

  - name: enable and start catalogue service 
    service:
      enable: true
      name: catalogue 
      start: started 
  
  - name: install mongodb-mongosh
    package:
      name: mongodb-mongosh 
      state: present 
  
  - name: load database
    shell: 
      mongosh --host "{{ mongodb_host }}" </app/db/master-data.js

  