- name: mongodb
  hosts: mongodb
  become: yes 
  tasks:

  - name: copy repo file 
    ansible.builtin.copy:
     src: mongo.repo
     dest: /etc/yum.repos.d/mongo.repo 

  - name: install mongodb
    package: 
      name: mongodb-org
      state: present

  - name: Start and enable MongoDB service
    ansible.builtin.service:
      name: mongod
      state: started
      enabled: true

  - name: allow mongodb to accept from all(0.0.0.0)
    replace:
      path:  /etc/mongod.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'
  

