- name: redis setup 
  hosts: redis 
  become: yes 
  tasks:
  - name: disbale default redis 
    service:
      name: redis 
      enable: false 
  - name: enable redis:7 
    service: 
      name: redis:7
      enable: true 
  - name: install redis 
    package:
      name: redis 
      state: present 
  - name: allow connections from all 
    replace:
      path: /etc/redis/redis.conf 
      regexp: '127.0.0.1'
      replace: '0.0.0.0'
  